version: "3.8"

services:
  app:
    container_name: hc-foundation-lite-dev
    image: hc-foundation-lite-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app/
    ports:
      - 3000:3000