version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: hc-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - hc-foundation-lite
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - hc-foundation-app
      - hc-2016-first
      - hc-2017-recurse
      - hc-2018-ternary
      - hc-2019-4d
      - hc-2020-101
      - hc-2021-hex
      - hc-2022-atlas
      - hc-2023-spyder

  hc-foundation-app:
    image: hackcambridge/hc-foundation-lite:v1.0.1
    container_name: hc-foundation-app
    ports:
      - 200:3000
    networks:
      - hc-foundation-lite
  
  hc-2016-first:
    image: hackcambridge/hc-2016-first:v1.0.0
    container_name: hc-2016-first
    ports:
      - 201:3000
    networks:
      - hc-foundation-lite
  
  hc-2017-recurse:
    image: hackcambridge/hc-2017-recurse:v1.0.0
    container_name: hc-2017-recurse
    ports:
      - 202:3000
    networks:
      - hc-foundation-lite
  
  hc-2018-ternary:
    image: hackcambridge/hc-2018-ternary:v1.0.0
    container_name: hc-2018-ternary
    ports:
      - 203:3000
    networks:
      - hc-foundation-lite

  hc-2019-4d:
    image: hackcambridge/hc-2019-4d:v1.0.0
    container_name: hc-2019-4d
    ports:
      - 204:3000
    networks:
      - hc-foundation-lite
  
  hc-2020-101:
    image: hackcambridge/hc-2020-101:v1.0.2
    container_name: hc-2020-101
    ports:
      - 205:8000
    networks:
      - hc-foundation-lite
  
  hc-2021-hex:
    image: hackcambridge/hc-2021-hex:v1.0.1
    container_name: hc-2021-hex
    ports:
      - 206:8000
    networks:
      - hc-foundation-lite
  
  hc-2022-atlas:
    image: hackcambridge/hc-2022-atlas:v1.0.0
    container_name: hc-2022-atlas
    ports:
      - 207:80
    networks:
      - hc-foundation-lite
  
  hc-2023-spyder:
    image: hackcambridge/hc-2023-spyder:v1.0.0
    container_name: hc-2023-spyder
    ports:
      - 208:80
    networks:
      - hc-foundation-lite

networks:
  hc-foundation-lite:
    driver: bridge